@startuml Secret Quest Platform Overview

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons

!include DEVICONS/google_cloud_platform.puml

LAYOUT_WITH_LEGEND()

System_Boundary(c1, "Secret Quest Platform") {
    System(iamSystem, "IAM", "Identity Platform", $sprite="google_cloud_platform")
    System(profileSystem, "Profile", "Profile System", $sprite="google_cloud_platform")
    System(loyaltySystem, "Loyalty", "Loyalty System", $sprite="google_cloud_platform")
    System(walletSystem, "Wallet", "Wallet System", $sprite="google_cloud_platform")
    System(gameStateSystem, "GameState", "Game State System", $sprite="google_cloud_platform")
}

@enduml