@startuml Secret Quest Platform Overview

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons

!include DEVICONS/google_cloud_platform.puml
!include DEVICONS/windows.puml
!include DEVICONS/android.puml
!include DEVICONS/unity_small.puml
!include DEVICONS/webplatform.puml

LAYOUT_WITH_LEGEND()


Person(gamer, "Gamers", "People that play games", $sprite="users")

System(desktopClient, "GodOfWar", "desktop", "Client Desktop", $sprite="windows")
System(mobileClient, "GodOfWar", "mobile", "Client Mobile", $sprite="android")
System(ps5Client, "GodOfWar", "console", "Client Console", $sprite="unity_small")


System_Boundary(c1, "Secret Quest Platform") {
    System(iamSystem, "IAM", "Identity System", $sprite="google_cloud_platform")
    System(profileSystem, "Profile", "Profile System", $sprite="google_cloud_platform")
    System(loyaltySystem, "Loyalty", "Loyalty System", $sprite="google_cloud_platform")
    System(walletSystem, "Wallet", "Wallet System", $sprite="google_cloud_platform")
    System(gameStateSystem, "GameState", "Game State System", $sprite="google_cloud_platform")
}

Rel(gamer, desktopClient, "Uses", "online")
Rel(gamer, mobileClient, "Uses", "online")
Rel(gamer, ps5Client, "Uses", "online")

Rel(desktopClient, iamSystem, "Uses", "online")
Rel(mobileClient, iamSystem, "Uses", "online")
Rel(ps5Client, iamSystem, "Uses", "online")

@enduml